## NumPy : Numerical Python 
    -It is an array 
    -It is core python library 
    -We are using numpy to perform the complex operation 
    -NumPy is an extension to the multidimensional array. 
    -Array is a collection of homogeneous/ Similar Kind data 
    
##### 1    why NumPy 
* Performing the operation on higher dimensional array -- Complex Operation in a machine learning each feature as a *dimension

* Scalar: Only Magnitude EX: Displacement 

* Vector: Magnitude as well as dimension 

* Dimensionaliity Reduction : PCA , TSNE 

##### 2 Complex Matrix Operation : 
* 1D : Vector 
* 2D : Matrix 
* 3D : Cube 
* ND : Tensors 

##### A. Matrix Multiplication : Costly / Complex 
* Because of the vectorization NumPy perform the multiplication in a faster way. 
    - Inverse 
    - rank 
    - Transpose 
    - Eigen Value & Eigen Vectors 
    - Determinant 
    - Linear Equation (a1x + b1yc + c = 0 ) 
    
    - Linear Equation can be solving using methods like:
     - 1 Simultaneous Equation 
     - Inversion , Reduction -- Matrix 
     - 3 LPP : Simplest Method 

##### 3. Another Use cases of NumPy is Numerical method and optimization ; 
* In a Mathematics we have two kind of method : 

    - 1.analytical method
    :If we have a formulation , method , theorem or axioms to solve a particular problem then we called it is analytical method  
             
     - 2.Numerical Method 
    :It is Kind of procedure or we can say approximmation ex: Newton raphson 
     - Vector Computing 
     - Stastical Operation : way of  solving the problem by collecting data and summarize 
##### 4 . It is Open  Source and freeware : 
    * It is available for everyone and freeware means it will no cost 
           
           

-----------------------------------------------------------------------
* For using the Numpy We have to import it  import numpy as np
  syntax ; 
  import -- keyword 
  numpy---- library name 
  np : alias 

In [1]:
pip install Numpy;

### Creating Numpy Array :
* np.array function
    - We are creating manually with the help of np.array()& always taking list as *argument*
    - It is in Fixed size 
    
    
    [ ] it is 1D Array 
    
    [[ ]] it is 2D Array
    
    ndim : It will gives the dimension of the numpy array 
        - syntax : array_name.ndim

In [1]:
import numpy as np 

In [2]:
array1 = np.array([11,12,13,14,15])

* np.array() : it is the way of creating array manually 

In [3]:
array1

array([11, 12, 13, 14, 15])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.ndim #it will show the array's dimension 

1

In [7]:
array2 = np.array([[1,2,3,4],[11,22,33,44]])# This is the 2 dimensional Array 

In [8]:
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
array2.ndim # this is how it shows the dimension of the array 

2

In [11]:
#Print 3D array (length , width , height)
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
array3.ndim

3

### Numpy array using arange():

*  we are creating the numpyy array with ar range with the format :-arange(start , Stop  , step)

In [3]:
import numpy as np 
array4 = np.arange(10)

In [4]:
print(array4)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr5 = np.arange(10,20,3)
arr5

array([10, 13, 16, 19])

In [7]:
#Addition of the matrix using list
a = [[1,2],[3,4]]
b = [[5,6],[5,8]]
c = [[0,0],[0,0]]

for i in range (len(a)):
    for j in range(len(b)):
        c[i][j]= a[i][j]+b[i][j]
print(c)

[[6, 8], [8, 12]]


In [8]:
#Addition of the matrix using Array (here for addition we didn't need for /iterate so it is time efficient)
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[5,8]])
a3 = a1+a2
print(a3)

[[ 6  8]
 [ 8 12]]


In [9]:
#MAtrix Multiplication using the 
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[5,8]])
a1*a2

array([[ 5, 12],
       [15, 32]])

In [10]:
a1.dot(a2)

array([[15, 22],
       [35, 50]])

In [12]:
a = [[1,2],[3,4]]
b = [[5,6],[5,8]]
c = [[0,0],[0,0]]

for i in range (len(a)):
    for j in range(len(b)):
        for k in range(len(b)):
            c[i][j]+= a[i][k]*b[i][k]
print(c)

[[17, 17], [47, 47]]


In [14]:
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [16]:
arr4 = np.zeros((5,5))
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
arr5 = np.ones((3,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr6  = np.eye(3,3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr7 = np.diag([1,2,3])
arr7

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [2]:
import numpy as np
a = np.diag([1,2,3,4,5])
b = np.diag([1,2,3,4,5])
c = a+b
c

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [6]:
x = np.linspace(10,20,10)
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [7]:
y = np.linspace(0,1)
y

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [11]:
r  = np.random.rand(5)#it will display 0. repeatedly cause the probability of shoulnot be greater than 1 #Uniform Distribution
r

array([0.70312878, 0.62528088, 0.37522088, 0.06366645, 0.31133015])

In [12]:
r2 = np.random.randn(5) # Standard Distribution 
r2

array([ 1.7510198 ,  1.19620314,  1.13853881,  3.0316483 , -1.32813952])

In [16]:
r3 = np.random.randint(10,20,3)
r3

array([11, 19, 13])

In [17]:
a1 = np.array([1,2,3,4])

In [19]:
a2 = a1.copy()
print(a2)

[1 2 3 4]


In [24]:
a2 = np.array([[5,6],[5,8]])

In [25]:
a2.shape

(2, 2)

In [26]:
a2.size

4

In [27]:
a2.dtype

dtype('int32')

In [30]:
a = [[1,2,3],[3,5,6]]
trace = 0 
for i in range(len(a)):
    for j in range(len(a)):
        if i == j:
            trace+=a[i][j]
print(trace)

6


In [31]:
p = np.array([[1,2,3],[3,5,6]])
np.trace(p)

6

In [32]:
# Transpose of a matrix using the numoy 
B = np.array([[1, 2], 
              [3, 4]])

B_transpose = B.T
print(B_transpose)


[[1 3]
 [2 4]]


In [34]:
# Function to transpose a matrix
def transpose_matrix(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    
    # Create an empty matrix with swapped dimensions
    transpose = [[0] * rows for _ in range(cols)]
    
    # Swap rows and columns
    for i in range(rows):
        for j in range(cols):
            transpose[j][i] = matrix[i][j]
    
    return transpose

# Example matrix
A = [[1, 2, 3], 
     [4, 5, 6]]

# Get transpose
A_transpose = transpose_matrix(A)

# Print result
print("Original Matrix:")
for row in A:
    print(row)

print("\nTransposed Matrix:")
for row in A_transpose:
    print(row)


Original Matrix:
[1, 2, 3]
[4, 5, 6]

Transposed Matrix:
[1, 4]
[2, 5]
[3, 6]


In [35]:
import numpy as np

# Define a square matrix
A = np.array([[4, 7], 
              [2, 6]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Original Matrix:\n", A)
print("\nInverse Matrix:\n", A_inv)


Original Matrix:
 [[4 7]
 [2 6]]

Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [36]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

if 30 in arr:
    print("30 is present in the array.")


30 is present in the array.


In [38]:
arr = [[10, 20, 30], 
       [40, 50, 60], 
       [70, 80, 90]]

item = 50
found = False

for i in arr:
    for j in arr:
        if i == j:
            found = True
            break
    if found:
        break

if found:
    print(f"{item} is present in the array.")
else:
    print(f"{item} is not present in the array.")


50 is present in the array.


In [40]:
a = np.array([1,2,3])
a*2

array([2, 4, 6])

In [41]:
a+2

array([3, 4, 5])

In [42]:
a**2

array([1, 4, 9])