##### Q1. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.


In [5]:
import numpy as np 

celsius = np.array([33,32,36,28,35.5,0,45.34])

fahrenhite = (celsius * 9/5)+32

print("Fahrenhite: ",fahrenhite)

Fahrenhite:  [ 91.4    89.6    96.8    82.4    95.9    32.    113.612]


###### Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.

In [5]:
import numpy as np
arr1 = np.array([10,20,30])
print("Size of array",len(arr1))
for i in arr1:
    print("Element in array: ",i)
if len(arr1)>0:
    print("Total bytes consumed by array:",len(arr1) * 8)


Size of array 3
Element in array:  10
Element in array:  20
Element in array:  30
Total bytes consumed by array: 24


##### Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [30]:
import numpy as np
a1 = np.array([12,11,14,1,2])
a2 = np.array([1,2,3,4,5])
result = np.array([ele in a1 for ele in a2])
result

array([ True,  True, False, False, False])

In [32]:
result1 = np.isin(a1,a2)
result1

array([False, False, False,  True,  True])

##### Write a NumPy program to find common values between two arrays.

In [41]:
import numpy as np 

b1 = np.array([23,12,11,14])
b2 = np.array([10,11,12,13])

common = []

for i in b1: 
    for j in b2:
        if i==j: 
            common.append(i)

common = np.array(common)            
print(common)
        

[12 11]


In [42]:
type(common)

numpy.ndarray

#####  Write a NumPy program to get the unique elements of an array

In [28]:
import numpy as np 

arr1 = np.array([1,2,2,2,1,3,4,4,5,6])

unique = []

for i in arr1:
    if i not in unique:
        unique.append(i)
unique = np.array(unique)

print(unique)

[1 2 3 4 5 6]


In [29]:
arr1_list = list(arr1)
unique = []

for i in arr1:
    if arr1_list.count(i)==1:
        unique.append(i)
        
non_repeat = np.array(unique)
print(non_repeat)

[3 5 6]


In [11]:
import numpy as np
arr1 = np.array([10,20,30])
size_of_array = arr1.itemsize
size_of_array


4

In [12]:
bytes_array = arr1.nbytes
bytes_array

12

In [13]:
size = arr1.size
size

3

In [60]:
import numpy as np 

d2= np.array([[1,1],[2,3]])

flattened = []

for i in d2:
    for j in i:
        flattened.append(j)
#(flattened)
        
unique=[]
for i  in flattened:
    count = 0 
    for j in flattened:
        if i==j:
            count+=1
    if count == 1:
        unique.append(i)

non_repeat = np.array(unique)
print(non_repeat)


[2 3]


###### Write a NumPy program to construct an array by repeating

In [6]:
import numpy as np 

a1 = np.array([1,2,3])

l1= []

for i in a1:
    for j in range(len(a1)):
        l1.append(i)
print(l1)

[1, 1, 1, 2, 2, 2, 3, 3, 3]


In [7]:
import numpy as np

arr = np.array([[4, 6], 
                [2, 1]])

print("Original array:")
print(arr)

# Sorting  (rows - vertically)
sorted_first_axis = np.sort(arr, axis=0)
print("\nSort along the first axis:")
print(sorted_first_axis)

# Sorting  (columns - horizontally)
sorted_last_axis = np.sort(arr, axis=1)
print("\nSort along the last axis:")
print(sorted_last_axis)


Original array:
[[4 6]
 [2 1]]

Sort along the first axis:
[[2 1]
 [4 6]]

Sort along the last axis:
[[4 6]
 [1 2]]
