In [1]:
#np_equal_array(a,b) checking each element 
import numpy as np 
a = np.array([1,2,3])
b = np.array([2,3,4])

In [4]:
np.array_equal(a,b)

False

### sorting in arrray 
* np.sort():it will sort in ascending order
    -it is not in-place sort
    
    numpy_array.sort():it will perform inplace sorting
    
    
    np.argsort():
    -it will perform the sorting on the basis of index of the numpy array
    
    


### Searching in NumPy Array 
    - np.where(condition): it will return the index of the element where cond is true 

In [5]:
a = np.array([3,4,5,1,7])
np.where(a>2)

(array([0, 1, 2, 4], dtype=int64),)

In [6]:
np.where(a==1)

(array([3], dtype=int64),)

In [8]:
np.where(a==0)

(array([], dtype=int64),)

#### np.nonzero() : it will return the index of the non zero element in the array.


In [9]:
#syntax: np.nonzero()
b = np.array([2,3,44,5,2,0,1,0])

In [10]:
np.nonzero(b)

(array([0, 1, 2, 3, 4, 6], dtype=int64),)

#### Np.extract(): 
      it will return the element based on the condition 
      - Syntax; np.extract(conditon , array_name)

In [14]:
c = np.array([2,3,11,5,66,43,12])

In [16]:
np.extract(c>5 , c)

array([11, 66, 43, 12])

#### Np.Append  
* Numpy is fixed in size 

- it is used to add the element in the numpy array 
- it will not make any changes directly in existing array 
- we have to create a new array to see the changes 
- it is taking extra array for aappend 

syntax: 
    np.append(array , element)

In [18]:
c = np.array([2,3,11,5,66,43,12])

In [19]:
np.append(c,12)

array([ 2,  3, 11,  5, 66, 43, 12, 12])

#### Np.insert()
    *it will insert the element into numpy array at the particular position 
    -but to see the changes we have to create another array. 
    
    syntax: 
        np.insert(arrayname , index , item )

In [20]:
np.insert(c,3,44)

array([ 2,  3, 11, 44,  5, 66, 43, 12])

#### Np.concatenate():

* It is used to concatenate the numpy array to another numpy array 

- it will create another numpy array 

- syntax:
     np.concatenate(array_name ,[i1,i2.....])

In [21]:
array1 = np.array([12,13,15,44,23])

In [23]:
array2 = np.concatenate((array1,c))
array2

array([12, 13, 15, 44, 23,  2,  3, 11,  5, 66, 43, 12])

#### Reshaping :    
    * it convert the one numpy array into another dimensions 
    
    - syntax; 
            1.array_name = np.array([]).reshape(x_dim,y_dim)
              array_name.reshape()
              
* If only one row present in a matrix 

In [25]:
a1 = np.array([1,2,3,4,5,6])

In [26]:
a1.shape

(6,)

In [29]:
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

##### Toggle the binary  matrix using bitwise operator 

In [4]:
import numpy as np 

a = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 1, 0]
])

a_tog = a^1
print(a_tog)

[[0 1 0]
 [1 0 1]
 [0 0 1]]


In [5]:
a = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 1, 0]
])

a_tog = 1-a
print(a_tog)

[[0 1 0]
 [1 0 1]
 [0 0 1]]


In [11]:
#Without using Vectorization/Numpy 
def double_a(a):
    double = []
    for i in a:
        double.append(i*2)
    return double
a = [1,2,3]
result = double_a(a)
print(result)


[2, 4, 6]


In [13]:
import numpy as np 

a = np.array([1,2,3])
doubled = a*2
print(doubled)

[2 4 6]


##### We can acessing the array element using their indexing , mentioning the row and column 

In [2]:
import numpy as np
a = np.array([1,2,3,4])
a[1]

2

#### Slicing in Array

In [4]:
a1 = np.arange(10)
a2 = np.arange(5)

In [5]:
a1[5:] = a2[::-1]

In [6]:
a1

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [7]:
b1 = np.array([2,3,4,5])
b2 = np.array([1,2,3,4])
b3 = np.array([2,3,4,5])

In [8]:
d = ((b1<=b2)) & (b1<=b3).all()

In [9]:
print(d)

[False False False False]


### Stastics in NumPy
##### 1 Descriptive Statistics
   * Descriptive statistics summarize and describe the main features of a dataset.

* It helps in understanding the basic characteristics of the data without making conclusions beyond the given dataset.

###### Types of Descriptive Statistics:

* Measures of Central Tendency: Mean, Median, Mode

* Measures of Dispersion: Range, Variance, Standard Deviation, Interquartile Range

* Measures of Shape: Skewness, Kurtosis

* Data Representation: Tables, Charts (Bar Graph, Histogram, Pie Chart, Box Plot)

* There are 2 Types of data 1. Numerical data and 2.Categorical Data

###### Mode : 
* It will work in the categorical data 
- It means maximum occurence of the datapoints 


##### 2. Inferential Statistics
* Inferential statistics allow us to make predictions or generalizations about a population based on sample data.

* It involves probability theory and hypothesis testing.

     Types of Inferential Statistics:

* Estimation: Point Estimation, Interval Estimation (Confidence Intervals)

* Hypothesis Testing: Null & Alternative Hypothesis, p-value, t-tests, chi-square test

* Regression Analysis: Linear Regression, Logistic Regression

* ANOVA (Analysis of Variance)

* Correlation Analysis: Pearson’s & Spearman’s Correlation

In [1]:
#write a python function to count all the square submatrix possible in given matrix



##### Correlation

    Correlation is a statistical measure that expresses the strength and direction of a relationship between two variables. It helps determine how one variable moves concerning another.

*  Types of Correlation
    Positive Correlation: If one variable increases, the other also increases (e.g., height and weight).

* Negative Correlation: If one variable increases, the other decreases (e.g., price of a product and demand).

* Zero Correlation: No relationship between the variables.

In [2]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

correlation = np.corrcoef(x, y)  # Pearson correlation matrix
print(correlation)


[[1. 1.]
 [1. 1.]]


In [3]:
a = np.random.randint(1, 100, (4, 5))
a

array([[75, 48, 27,  5, 90],
       [29, 65, 31, 18, 22],
       [92, 71,  1, 94, 92],
       [57, 36, 71, 89, 23]])

In [6]:
fill = (a>15) & (a%2==0)

In [7]:
fill

array([[False,  True, False, False,  True],
       [False, False, False,  True,  True],
       [ True, False, False,  True,  True],
       [False,  True, False, False, False]])

In [8]:
a[fill]

array([48, 90, 18, 22, 92, 94, 92, 36])

##### Broadcasting In NumPy
* Its a ability to expand the array to perform the operations with the larger array.

* Broadcasting is a process to perform the operation of small matrices and large matrix 

* With the help of this concept different size matrix operation can perform 

In [9]:
aa = np.ones((3,3))+4
aa

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [27]:
aa4 = np.arange(12).reshape(3,4)
aa5 = np.arange(12).reshape(4,3)
aa4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
aa5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
aa4 + aa5

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [43]:
a1 = np.arange(18).reshape(3,6)
a2 = np.arange(3).reshape(3,1)



In [44]:
a1+a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19]])

##### RMO & CMO  ( array is faster because of RMO)

In [2]:
# Concatenate 2 matrices :
import numpy as np
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6] ,[7,8]])

a1+a2

array([[ 6,  8],
       [10, 12]])

In [3]:
np.concatenate([a1,a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
np.concatenate([a1,a2]).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.hstack([a1,a2]) # it is concatenate horizontally 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
np.vstack([a1,a2]) # It is conatenate Vertically 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Copy & View

*Copy()* : 
* When we use copy() , it will create duplicate array with different buffer.

* The changes made in copied array will not effect the orignal array and vice versa 

* When we are using copy we required extra memory buffer so it is not memory efficient 

* So whenever we use copy() we have the store the data aswell as its meta deta(all the details)

*View()*:
* When we will use view() it will not create the copy, it will create the view 
* both orignal array and views are at the same place.
- So we don't need extra buffer to store the data but we required to store the metadata to differentia two array 
- so view() is memory efficient 

- To ch3ck the both array at the same space : np.shares_memory(array1,array2)
                

In [11]:
z1 = np.array([12,13,14,15])
x1 = z1.copy()
print(x1)

[12 13 14 15]


In [15]:
x1[0] = 10
print(x1)
print(z1)

[10 13 14 15]
[12 13 14 15]


In [14]:
z2 = np.array([1,2,3,4,5])
v1 = z2.view()

v1[0]=99
print(v1)

print(z2)

[99  2  3  4  5]
[99  2  3  4  5]


In [18]:
np.shares_memory(z2,v1) #View

True

In [19]:
np.shares_memory(z1,x1) #Copy 

False

##### Flatening 

In [20]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("Flattened Array:", flat_arr)


Original Array:
 [[1 2]
 [3 4]]
Flattened Array: [1 2 3 4]


In [21]:
ravel_arr = arr.ravel()
ravel_arr[0] = 100  # Modify the view

print("Modified Flattened Array:", ravel_arr)
print("Original Array:\n", arr)  # arr is modified!


Modified Flattened Array: [100   2   3   4]
Original Array:
 [[100   2]
 [  3   4]]
